sudo: required
services:
- docker
env:
  global:
    # Ensure the downloaded SDK is first on the PATH
    - PATH=${HOME}/google-cloud-sdk/bin:$PATH
    # Ensure the install happens without prompts
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
language: node_js
node_js:
- '6'
before_install:
- npm install grunt-cli -g
install:
- openssl aes-256-cbc -K $encrypted_244bfbacb3b9_key -iv $encrypted_244bfbacb3b9_iv -in credentials.tar.enc -out credentials.tar -d
- tar -xvf credentials.tar
- mv keys.js config/keys.js
- rm gc_cred.json
- npm install
- docker build -t cloudboost/analytics:2.0.$TRAVIS_BUILD_NUMBER .
- docker build -t cloudboost/analytics:latest .
after_success:
#Deploy. 
#Docker Login
- docker login --username $DOCKERUSERNAME --password $DOCKERPASSWORD --email $DOCKEREMAIL
#Push docker images. 
- docker push cloudboost/analytics:2.0.$TRAVIS_BUILD_NUMBER
- docker push cloudboost/analytics:latest
# Make sure SDK is downloaded - cache once it's working
- openssl aes-256-cbc -K $encrypted_244bfbacb3b9_key -iv $encrypted_244bfbacb3b9_iv -in credentials.tar.enc -out credentials.tar -d
- tar -xvf credentials.tar
- curl https://sdk.cloud.google.com | bash;
# List the SDK contents to ensure it's downloaded
- ls -l ${HOME}/google-cloud-sdk/bin
# Ensure the correct gcloud is being used
- which gcloud
# Print the gcloud version and make sure it's something
- gcloud --version
#Activate Google Cloud SDK with your project
- gcloud auth activate-service-account --key-file gc_cred.json
#Install Kubectl
- gcloud components install kubectl
- gcloud container clusters get-credentials $GOOGLECLUSTERNAME --zone $GOOGLEZONE --project $GOOGLEPROJECT
#Upload to Kubernetes for deployment.
- kubectl config view
- kubectl rolling-update cloudboost-analytics --image=cloudboost/analytics:latest --image-pull-policy=Always
#Notify Team on Slack
notifications:
  slack: cloudboost:gm7nWJDLDtBRyF75VKLKOoMW
