sudo: required
services:
- docker
env:
  global:
    # Ensure the install happens without prompts
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
language: node_js
node_js:
- '6'
before_install:
- npm install
install:
- docker build -t cloudboost/analytics:2.0.$TRAVIS_BUILD_NUMBER .
- docker build -t cloudboost/analytics:latest .
- docker run --name analytics -e  HOSTED_SECUREKEY=$HOSTED_SECUREKEY -e  LOG_TOKEN=$LOG_TOKEN -p 5555:5555 -it -d cloudboost/analytics:2.0.$TRAVIS_BUILD_NUMBER 
- sleep 30s
- curl http://localhost:5555/status
- docker logs analytics
- docker logs cloudboost
after_success:
- echo "OK"
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=2.0.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$GITLOGIN@github.com/CloudBoost/analytics --tags
  - ls -R
deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "README.md"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
after_deploy:
# Docker Deploy.
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login --username $DOCKERUSERNAME --password $DOCKERPASSWORD --email $DOCKEREMAIL;
  docker push cloudboost/analytics:2.0.$TRAVIS_BUILD_NUMBER;
  docker push cloudboost/analytics:latest;
  fi
branches:
  except:
    - /^*-v[0-9]/
#Notify Team on Slack
notifications:
  slack: cloudboost:gm7nWJDLDtBRyF75VKLKOoMW
